type: class
name: default
icon: PLAYER_HEAD
is-in-shop: false
level: 1
groups: []

children: []
pre-reqs: []

mana-title: mana
mana-per-second: 1
max-mana: 50
max-health: 18

allowed-actions:
  - BOW
  - CROSSBOW
  - TRIDENT
  - DIAMOND_SWORD
  - DIAMOND_AXE
  - DIAMOND_HELMET
  - DIAMOND_CHESTPLATE
  - DIAMOND_LEGGINGS
  - DIAMOND_BOOTS
  - SHARPNESS.5
  - POWER.5
  - PROTECTION.4

spells:
  1:
    - g:damage
    - g:disable
  2:
    - g:debuff
    - g:damage-over-time
  3:
    - g:buff
    - g:chase
    - g:heal
  4:
    - g:escape
    - g:non-combat
    - g:allowed-action

