black-list-worlds:
- Resource
- Midgard_nether
- Midgard_the_end
- world_nether
- world_the_end
- MedievalSpawn_nether
- MedievalSpawn_the_end
default-language: en
allow-civ-item-sharing: false
#put rings above towns
town-rings: true
town-ring-material: "GLOWSTONE"
#how long a town sits at zero before protection ends
#if destroy towns at zero is on, then this does nothing
town-grace-period: 43200 #12 hours
#ignore other plugins when checking if an explosion is cancelled
#before reducing power
explosion-override: false
destroy-towns-at-zero: false #should towns be destroyed if at zero power
max-town-tax: 50.0
use-starter-book: true
price-multiplier: 1.0 #multiplier for prices before adding base price
price-base: 0.0 #added to all item prices
exp-modifier: 0.2
jail-time-seconds: 300
#cooldown before spawning a new villager in seconds
villager-cooldown: 300
#stops arrow turrets from shooting at monsters
disable-arrow-turret-shooting-at-mobs: false
#cooldown before killing the same player reduces the town power
death-grace-period-seconds: 60
#how long a player is considered in combat after taking or dealing damage
combat-tag-duration: 60
#should food heal in combat?
allow-food-heal-in-combat: true
#should players be able to teleport while in combat?
allow-teleporting-during-combat: false
#use the class and spell system from Civs
use-classes-and-spells: false
points:
  killstreak: 0.1
  killjoy: 0.2
  kill: 1
  death: -1
  half-health: 0.5
  quarter-health: 1
money:
  killstreak: 1
  killjoy: 1
  kill: 1
  karma: 0.1
karma-per-kill: 1
karma-per-kill-streak: 1
#How often should karma be cut by 50%? Adds 50% to negative karma. Subtracts 50% from positive karma.
karma-depreciate-period: 43200 #12 hours
power-per-kill: 12
power-per-npc-kill: 4
folders:
  farms: STONE_HOE
  towns: GLOWSTONE
  shops: EMERALD
  utilities: REDSTONE
  housing: RED_BED
  defense: ARROW
  quarries: STONE_SHOVEL
  factories: PISTON
  offense: TNT
  mines: STONE_PICKAXE
  woodworks: OAK_LOG
  animals: SHEEP_SPAWN_EGG
  npchousing: VILLAGER_SPAWN_EGG
  trading: EMERALD_ORE
levels:
- DIRT
- OAK_LOG
- COAL_BLOCK
- IRON_BLOCK
- GOLD_BLOCK
- EMERALD_BLOCK
- DIAMOND_BLOCK
custom-items:
  jade:
  - "Redeem 16 Jade at a Jade shop for $800"
item-groups:
  sign: SIGN,WALL_SIGN
  wool: RED_WOOL,BLACK_WOOL,BLUE_WOOL,BROWN_WOOL,CYAN_WOOL,GRAY_WOOL,GREEN_WOOL,LIGHT_BLUE_WOOL,LIGHT_GRAY_WOOL,LIME_WOOL,MAGENTA_WOOL,ORANGE_WOOL,PINK_WOOL,PURPLE_WOOL,WHITE_WOOL,YELLOW_WOOL
  wood: OAK_PLANKS,SPRUCE_PLANKS,BIRCH_PLANKS,JUNGLE_PLANKS,DARK_OAK_PLANKS,ACACIA_PLANKS
  log: OAK_LOG,SPRUCE_LOG,BIRCH_LOG,JUNGLE_LOG,DARK_OAK_LOG,ACACIA_LOG,STRIPPED_OAK_LOG,STRIPPED_SPRUCE_LOG,STRIPPED_BIRCH_LOG,STRIPPED_JUNGLE_LOG,STRIPPED_DARK_OAK_LOG,STRIPPED_ACACIA_LOG,OAK_WOOD,SPRUCE_WOOD,BIRCH_WOOD,JUNGLE_WOOD,DARK_OAK_WOOD,ACACIA_WOOD,STRIPPED_OAK_WOOD,STRIPPED_SPRUCE_WOOD,STRIPPED_BIRCH_WOOD,STRIPPED_JUNGLE_WOOD,STRIPPED_DARK_OAK_WOOD,STRIPPED_ACACIA_WOOD
  fence: OAK_FENCE,BIRCH_FENCE,SPRUCE_FENCE,JUNGLE_FENCE,DARK_OAK_FENCE,ACACIA_FENCE,IRON_BARS,MOSSY_COBBLESTONE_WALL,COBBLESTONE_WALL,NETHER_BRICK_FENCE
  fencegate: OAK_FENCE_GATE,BIRCH_FENCE_GATE,SPRUCE_FENCE_GATE,JUNGLE_FENCE_GATE,DARK_OAK_FENCE_GATE,ACACIA_FENCE_GATE
  door: OAK_DOOR,ACACIA_DOOR,DARK_OAK_DOOR,SPRUCE_DOOR,BIRCH_DOOR,JUNGLE_DOOR,IRON_DOOR
  glass: GLASS,GLASS_PANE,RED_STAINED_GLASS_PANE,BLACK_STAINED_GLASS_PANE,BLUE_STAINED_GLASS_PANE,BROWN_STAINED_GLASS_PANE,CYAN_STAINED_GLASS_PANE,GRAY_STAINED_GLASS_PANE,GREEN_STAINED_GLASS_PANE,LIGHT_BLUE_STAINED_GLASS_PANE,LIGHT_GRAY_STAINED_GLASS_PANE,LIME_STAINED_GLASS_PANE,MAGENTA_STAINED_GLASS_PANE,ORANGE_STAINED_GLASS_PANE,PINK_STAINED_GLASS_PANE,PURPLE_STAINED_GLASS_PANE,WHITE_STAINED_GLASS_PANE,YELLOW_STAINED_GLASS_PANE,RED_STAINED_GLASS,BLACK_STAINED_GLASS,BLUE_STAINED_GLASS,BROWN_STAINED_GLASS,CYAN_STAINED_GLASS,GRAY_STAINED_GLASS,GREEN_STAINED_GLASS,LIGHT_BLUE_STAINED_GLASS,LIGHT_GRAY_STAINED_GLASS,LIME_STAINED_GLASS,MAGENTA_STAINED_GLASS,ORANGE_STAINED_GLASS,PINK_STAINED_GLASS,PURPLE_STAINED_GLASS,WHITE_STAINED_GLASS,YELLOW_STAINED_GLASS
  window: GLASS,GLASS_PANE,IRON_BARS,RED_STAINED_GLASS_PANE,BLACK_STAINED_GLASS_PANE,BLUE_STAINED_GLASS_PANE,BROWN_STAINED_GLASS_PANE,CYAN_STAINED_GLASS_PANE,GRAY_STAINED_GLASS_PANE,GREEN_STAINED_GLASS_PANE,LIGHT_BLUE_STAINED_GLASS_PANE,LIGHT_GRAY_STAINED_GLASS_PANE,LIME_STAINED_GLASS_PANE,MAGENTA_STAINED_GLASS_PANE,ORANGE_STAINED_GLASS_PANE,PINK_STAINED_GLASS_PANE,PURPLE_STAINED_GLASS_PANE,WHITE_STAINED_GLASS_PANE,YELLOW_STAINED_GLASS_PANE,RED_STAINED_GLASS,BLACK_STAINED_GLASS,BLUE_STAINED_GLASS,BROWN_STAINED_GLASS,CYAN_STAINED_GLASS,GRAY_STAINED_GLASS,GREEN_STAINED_GLASS,LIGHT_BLUE_STAINED_GLASS,LIGHT_GRAY_STAINED_GLASS,LIME_STAINED_GLASS,MAGENTA_STAINED_GLASS,ORANGE_STAINED_GLASS,PINK_STAINED_GLASS,PURPLE_STAINED_GLASS,WHITE_STAINED_GLASS,YELLOW_STAINED_GLASS,NETHER_BRICK_FENCE,OAK_FENCE,BIRCH_FENCE,SPRUCE_FENCE,JUNGLE_FENCE,DARK_OAK_FENCE,ACACIA_FENCE,IRON_BARS
  primary: OAK_PLANKS,SPRUCE_PLANKS,JUNGLE_PLANKS,BIRCH_PLANKS,DARK_OAK_PLANKS,ACACIA_PLANKS,CLAY,SMOOTH_SANDSTONE,SMOOTH_RED_SANDSTONE,STONE_BRICKS,OAK_SLAB,BIRCH_SLAB,SPRUCE_SLAB,JUNGLE_SLAB,ACACIA_SLAB,DARK_OAK_SLAB,QUARTZ_SLAB,QUARTZ_BLOCK,PACKED_ICE,RED_WOOL,BLACK_WOOL,BLUE_WOOL,BROWN_WOOL,CYAN_WOOL,GRAY_WOOL,GREEN_WOOL,LIGHT_BLUE_WOOL,LIGHT_GRAY_WOOL,LIME_WOOL,MAGENTA_WOOL,ORANGE_WOOL,PINK_WOOL,PURPLE_WOOL,WHITE_WOOL,YELLOW_WOOL,TERRACOTTA,RED_TERRACOTTA,BLACK_TERRACOTTA,BLUE_TERRACOTTA,BROWN_TERRACOTTA,CYAN_TERRACOTTA,GRAY_TERRACOTTA,GREEN_TERRACOTTA,LIGHT_BLUE_TERRACOTTA,LIGHT_GRAY_TERRACOTTA,LIME_TERRACOTTA,MAGENTA_TERRACOTTA,ORANGE_TERRACOTTA,PINK_TERRACOTTA,PURPLE_TERRACOTTA,WHITE_TERRACOTTA,YELLOW_TERRACOTTA,PRISMARINE,PURPUR_BLOCK,NETHER_BRICKS,POLISHED_ANDESITE,POLISHED_DIORITE,POLISHED_GRANITE
  secondary: COBBLESTONE,OAK_LOG,SPRUCE_LOG,BIRCH_LOG,JUNGLE_LOG,DARK_OAK_LOG,ACACIA_LOG,SANDSTONE,RED_SANDSTONE,BRICKS,COBBLESTONE_SLAB,MOSSY_COBBLESTONE,SNOW_BLOCK,QUARTZ_PILLAR,CHISELED_QUARTZ_BLOCK,RED_GLAZED_TERRACOTTA,BLACK_GLAZED_TERRACOTTA,BLUE_GLAZED_TERRACOTTA,BROWN_GLAZED_TERRACOTTA,CYAN_GLAZED_TERRACOTTA,GRAY_GLAZED_TERRACOTTA,GREEN_GLAZED_TERRACOTTA,LIGHT_BLUE_GLAZED_TERRACOTTA,LIGHT_GRAY_GLAZED_TERRACOTTA,LIME_GLAZED_TERRACOTTA,MAGENTA_GLAZED_TERRACOTTA,ORANGE_GLAZED_TERRACOTTA,PINK_GLAZED_TERRACOTTA,PURPLE_GLAZED_TERRACOTTA,WHITE_GLAZED_TERRACOTTA,YELLOW_GLAZED_TERRACOTTA,DARK_PRISMARINE,PURPUR_PILLAR,STRIPPED_OAK_LOG,STRIPPED_SPRUCE_LOG,STRIPPED_BIRCH_LOG,STRIPPED_JUNGLE_LOG,STRIPPED_DARK_OAK_LOG,STRIPPED_ACACIA_LOG,OAK_WOOD,SPRUCE_WOOD,BIRCH_WOOD,JUNGLE_WOOD,DARK_OAK_WOOD,ACACIA_WOOD,STRIPPED_OAK_WOOD,STRIPPED_SPRUCE_WOOD,STRIPPED_BIRCH_WOOD,STRIPPED_JUNGLE_WOOD,STRIPPED_DARK_OAK_WOOD,STRIPPED_ACACIA_WOOD
  roof: ACACIA_STAIRS,OAK_STAIRS,BIRCH_STAIRS,JUNGLE_STAIRS,SPRUCE_STAIRS,DARK_OAK_STAIRS,BRICK_STAIRS,COBBLESTONE_STAIRS,SMOOTH_SANDSTONE,SMOOTH_RED_SANDSTONE,STONE_BRICKS,QUARTZ_SLAB,COBBLESTONE_SLAB,QUARTZ_STAIRS,SANDSTONE_STAIRS,RED_SANDSTONE_STAIRS,DARK_PRISMARINE_STAIRS,PRISMARINE_BRICK_STAIRS,PURPUR_STAIRS,STONE_BRICK_STAIRS,OAK_SLAB,BIRCH_SLAB,SPRUCE_SLAB,JUNGLE_SLAB,ACACIA_SLAB,DARK_OAK_SLAB,QUARTZ_STAIRS
  bed: RED_BED,BLACK_BED,BLUE_BED,BROWN_BED,CYAN_BED,GRAY_BED,GREEN_BED,LIGHT_BLUE_BED,LIGHT_GRAY_BED,LIME_BED,MAGENTA_BED,ORANGE_BED,PINK_BED,PURPLE_BED,WHITE_BED,YELLOW_BED
  stairs: QUARTZ_STAIRS,SANDSTONE_STAIRS,RED_SANDSTONE_STAIRS,ACACIA_STAIRS,OAK_STAIRS,BIRCH_STAIRS,JUNGLE_STAIRS,SPRUCE_STAIRS,DARK_OAK_STAIRS,BRICK_STAIRS,COBBLESTONE_STAIRS,DARK_PRISMARINE_STAIRS,PRISMARINE_BRICK_STAIRS,PURPUR_STAIRS,STONE_BRICK_STAIRS,QUARTZ_STAIRS
  vertical: LADDER,QUARTZ_STAIRS,SANDSTONE_STAIRS,RED_SANDSTONE_STAIRS,ACACIA_STAIRS,OAK_STAIRS,BIRCH_STAIRS,JUNGLE_STAIRS,SPRUCE_STAIRS,DARK_OAK_STAIRS,BRICK_STAIRS,COBBLESTONE_STAIRS,DARK_PRISMARINE_STAIRS,PRISMARINE_BRICK_STAIRS,PURPUR_STAIRS,STONE_BRICK_STAIRS
groups:
  shop: 3
  quarry: 12
  housing: 3
  superregion: 1

#region port configs
port:
  mana: 0
  warmup: 5
  cooldown: 60
  money: 0
  damage: 0
  stamina: 0
  port-during-combat: false
  #list of items needed but not consumed
  #reagents: []
  slow-warmup: true

tutorial:
  use-tutorial: true
  use-guide: true
  url: "https://youtu.be/pa_rfrpUAS8"
top-guide-spacer: "-----------------Civs-----------------"
bottom-guide-spacer: "--------------------------------------"
civs-chat-prefix: "@{GREEN}[Civs]"
civs-item-prefix: "Civs"

allow-changing-gov-type: true
default-gov-type: "DICTATORSHIP"
# for governments that use voting, for how long should a player be elected?
days-between-elections: 7
