package org.redcastlemedia.multitallented.civs.towns;

public enum GovernmentType {
    OLIGARCHY,
    DEMOCRACY,
    DICTATORSHIP,
    COMMUNISM,
    COOPERATIVE,
    ANARCHY,
    DISESTABLISHMENT,
    LIBERTARIAN,
    SOCIALISM,
    DEMOCRATIC_SOCIALISM,
    KRATEROCRACY,
    MERITOCRACY,
    CYBERSYNACY, // ai
    TRIBALISM,
    FEUDALISM,
    COLONIALISM,
    CAPITALISM,
    LIBERTARIAN_SOCIALISM,
    IDIOCRACY
}
