author: Multitallented
database: false
description: An RPG plugin that focuses on land management via towns and regions.
main: org.redcastlemedia.multitallented.civs.Civs
name: Civs
load: POSTWORLD
version: 1.5.8
api-version: 1.14
depend: [Vault]
softdepend:
- PlaceholderAPI
- MultiverseCore
- MMOItems
commands:
   cv:
      aliases: ['township', 'townships', 'towns', 'town', 'to', 'hs', 'towny', 'fa', 'f', 'faction', 'civs', 'civ']
      description: Civs commands
      usage: /<command>
permissions:
   civs.join:
       description: Allows players to join towns
       default: true
   civs.choose:
       description: Allows a player to choose classes
       default: true
   civs.shop:
       description: Allows players to use the shop
       default: true
   civs.admin:
      description: Lets you use admin commands and bypass protections
      default: op
loadafter: [Vault, PlaceholderAPI]
